PLAYER_1 = 1
PLAYER_2 = -1
NEUTRAL = 0

EMPTY = 0
PEASANT_P1 = 1
WARRIOR_P1 = 2
PEASANT_P2 = -1
WARRIOR_P2 = -2

PEASANT_COST = 10
PEASANT_UPKEEP = 1
WARRIOR_COST = 20
WARRIOR_MERGE_COST = 0
WARRIOR_UPKEEP = 3
INCOME_PER_CELL = 1

BOARD_SIZE = 10
MAX_TURNS = 50
